### PR TITLE
Updated table of contents to link to md files, suggested summary for appendix

### PR DESCRIPTION
**Pull request by SyntaxPolice**
This commit applies to the various cover.md files.

Again, not positive about toolchain here; perhaps the generated HTML files used section headings as shown. If so, please discard.

Also added suggested summary in 63b appendix A to assist with clarity on cross-reference from section 5.

### CODE REVIEW

**Comment by paul-grassi** [comment]
@SyntaxPolice if we accepted this, than the pages site won't work.  We prefer the pages site to work over the .md.  I can likely cherry pick the appendix updates and skip the other commits.

**Comment by SyntaxPolice** [comment]
I see. I wondered if it was something like that. No worries. Want me to
make a new PR?

peace,

  Isaac, sent from a mobile device

**Comment by paul-grassi** [comment]
yes please!

**Comment by SyntaxPolice** [comment]
Created [new pull request](https://github.com/usnistgov/800-63-3/pull/231) without the index file changes.

**Pull request closed without merging**
