### PR TITLE
Add "Memorized Secret" definition

### PR DESCRIPTION
**Pull request by jweden**
Need definition for "Memorized Secret".  Carried over similar definition of "Memorized Secret Token" from: http://nvlpubs.nist.gov/nistpubs/ir/2015/NIST.IR.8014.pdf

### CODE REVIEW

**Comment by jimfenton** [comment]
Thanks for pointing out that we don't have this definition. As for the wording, I lean somewhat toward the definition at the beginning of 5.1.1, in particular that is intended to be memorable by the user. Also, memorized secrets aren't always shared between the subscriber and verifier: a memorized secret that is used to activate a multi-factor crypto authenticator being a counterexample. Is it OK if we substitute the 5.1.1 definition (probably just the first sentence)?

**Comment by jweden** [comment]
Was just looking at 5.1.1 too.  Yeah, that makes sense.

**Comment by jimfenton** [comment]
OK then. Two things:

1. Please also open an issue, so our list of resolved issues is all in one place. We'll use this pull request to close that issue.
2. Your choice, either push another commit to your branch to use the 5.1.1 wording, or I can do that if your branch is set up in the usual way by GitHub. Let me know your preference.

**Comment by jweden** [comment]
Done: https://github.com/usnistgov/800-63-3/issues/542

**Comment by jimfenton** [comment]
Closes #542.

**Review by paul-grassi — APPROVED** [review]

**Pull request merged**
